### ISSUE TITLE
Video disappearing after a couple of seconds

### ISSUE THREAD

**Issue by raikirii** [Aldrog/TwitchTube#1]
Hey Aldrog,

thanks for the great app. I am already impressed by its features and how good it looks. 

When I start to watch a stream the video loads and plays for a couple of seconds then disappears. chat is working normally just the video turns to empty space. when i tap on the space where the video should be, the stream returns and stops again after a couple of seconds.

So it is not useable for me, yet. But still a nice start! Keep up the great work. If I can help in any way please let me know how.

**Comment by Aldrog** [comment]
Thank you for reporting the issue. I will look at what can I do with it after getting home.
By the way, mobile quality seems to work OK for now.

**Comment by raikirii** [comment]
this issue happens with all quality settings for me.

**Comment by Aldrog** [comment]
I've added debug info logging for video and also a small fix that resumes video when it stops (looks like it stops when buffer isn't full).
https://github.com/Aldrog/TwitchTube/releases/tag/v0.2.1-dev
@raikirii, can you please check if it works and if not send me a log.
You can save a log by calling `harbour-twitchtube 2> /path/to/log/file` from console.

**Comment by raikirii** [comment]
The resuming works. just a short time no video and it resumes automatically. I have made two logs for you.

http://pastebin.com/uztF5nPj
http://pastebin.com/ngWaqvFb

Hope that helps. Let me know if you need anything else.

**Comment by Aldrog** [comment]
Thanks a lot. Logs don't contain any errors so I'm closing the issue. Of course there should be some loading indicator when video stops but I'll leave it until next release.

**Comment by raikirii** [comment]
It just seems weird to me, because I have a 50 Mbit/s internet connection and twitch has no lags on other devices. I don't think it's a buffering issue. But okay. I'll give it time ;)

I appreciate your fast response. Keep up the great work.

**Comment by Aldrog** [comment]
Well, maybe I should make more investigation, but it requires changing QtMultimedia code so I'm not going to touch it untill all the features are ready.

**Comment by Aldrog** [comment]
@raikirii can you make a screenshot of working video so I can put it on openrepos?

**Comment by raikirii** [comment]
Here ya go!

![20150217190209](https://cloud.githubusercontent.com/assets/4764204/6234295/26225aae-b6da-11e4-85bb-a93ff67c8be8.jpg)
![20150217190855](https://cloud.githubusercontent.com/assets/4764204/6234294/26221486-b6da-11e4-9f24-7b1e4ff29aeb.jpg)
![20150217190904](https://cloud.githubusercontent.com/assets/4764204/6234296/2649bffe-b6da-11e4-84e4-90a572c3c349.jpg)
![20150217191002](https://cloud.githubusercontent.com/assets/4764204/6234297/264f447e-b6da-11e4-8930-a8e5607b4839.jpg)
![20150217191117](https://cloud.githubusercontent.com/assets/4764204/6234299/2653b41e-b6da-11e4-807e-7c67fbca4b38.jpg)
![20150217191350](https://cloud.githubusercontent.com/assets/4764204/6234298/26533200-b6da-11e4-89d8-fd5ec8b5c7a3.jpg)

**Comment by Aldrog** [comment]
Nice! Thanks a lot for your help.
