### ISSUE TITLE
Check for alternative stream quality names

### ISSUE THREAD

**Issue by k0rmarun** [Aldrog/TwitchTube#15]
Some channels such as dota2ti have different stream quality names such as "144p30, 240p30, 360p30, 480p30, 540p30, 720p30, 720p60" instead of the common ones "mobile low medium high source".
These should be matched automatically and/or used in stream quality name settings menu (QualityChooserPage.qml).

**Comment by Aldrog** [comment]
Thanks for reporting this :) I'll fix it ASAP but it's not likely to arrive at Jolla Store before the start of the main event.

**Comment by Aldrog** [comment]
@k0rmarun I've sent a fixed version to Jolla Store. While it waits for approval you can take rpms from here https://github.com/Aldrog/TwitchTube/releases/tag/v1.1.1

**Comment by k0rmarun** [comment]
@Aldrog Thank you very much. Works like a charm on both phone and tablet

**Comment by Aldrog** [comment]
v1.1.1 is on the Store just in time :)
