### ISSUE TITLE
TwitchTube crashes when opening streams

### ISSUE THREAD

**Issue by ghost** [Aldrog/TwitchTube#18]
What the title says more or less.
Reproduce:
Open TwitchTube, pick any stream, app crashes as soon as the stream loads. You get chat for a couple seconds until the video tries to start playing.

What should've happened:
Video played ;)

Disclosure: I am using an alpha port of Sailfish, however I think the problem is with the app because every other app I can find and install via storeman works fine. One possibility, though: does TwitchTube utilize the system browser in any way, or do the gecko IPC thing? If so, that would explain the crash (this particular port has a crashy default browser)

**Comment by ghost** [comment]
After more testing this is almost certainly an issue with my rom.

**Comment by Aldrog** [comment]
IDK what you rom is but on Sailfish X it's even worse: playback start can sometimes cause the whole OS to crash (and reboot).

**Comment by ghost** [comment]
I'd say that's worthy of a different bug. This was a specific problem on the OnePlus 2 with the system's gstreamer libraries, I was able to get it fixed. Presumably gstreamer works properly on the sailfish X.
