### ISSUE TITLE
Screen goes blank while watching stream

### ISSUE THREAD

**Issue by Aldrog** [Aldrog/TwitchTube#3]
Hi @Termitebug,
I think I found a possible location of the bug in headers includings. If it's true, commit c48aeb06fbe6facc5e102495c5f50e081b0ea28f should fix it. Could you give it a try?
https://github.com/Aldrog/TwitchTube/releases/tag/v1.0.0-alpha.2

**Comment by Termitebug** [comment]
Yes, I tried both 0.2 and 0.9 versions. They both have this same screen issue. Therefore I tried this "fixed" version but the application fails to start every time. Can't remember the terminal log command to create a trace file. I only did normal user operations (install/upgrade/remove) from 0.2 to 1.0alpha. Were too buzy to mess/clean with .config files&folders. My system version is 1.1.9.28.

**Comment by Aldrog** [comment]
@Termitebug I've just uploaded a rebuild of the app on experimental SDK. You can grab it on the same [version tag](https://github.com/Aldrog/TwitchTube/releases/tag/v1.0.0-alpha.2). Not sure if it changed anything, but crash at the start sounds like a broken build.

> Can't remember the terminal log command to create a trace file.

You can launch `harbour-twitchtube` from terminal and simply copy-paste the output, or append `&> filename` to it to write the output to file.

I'm really sorry about taking your time, hope to get a tablet soon so I won't need help just to check if the app works.

**Comment by Termitebug** [comment]
It seems your the experimental SDK produces broken builds. RPM file size is half of a previous successful build (0.9.0-1). Launching the app from terminal prints "missing binary in <code>/usr/bin/</code>"

**Comment by Aldrog** [comment]
@Termitebug [new build](https://github.com/Aldrog/TwitchTube/releases/download/v1.0.0-alpha.2/harbour-twitchtube-0.90.1-3.armv7hl.rpm) 36 KB and it launches successfully on my phone with SailfishOS 1.1.0.38

**Comment by Aldrog** [comment]
@Termitebug has the issue gone? I can't check it since Sailfish port for my SGS3 doesn't support automatic screen blanking at all.

**Comment by Termitebug** [comment]
Issue still persists. Application log does mention screen blanking is turned off. But screen goes blank:

<code> SailfishOS 1.1.9.28 (Eineheminlampi) (armv7hl)
'---
[nemo@Jolla ~]$ harbour-twitchtube

[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL

[D] loadGames:37 - https://api.twitch.tv/kraken/games/top?limit=16&offset=0

[D] :30 - Error accessing url https://api.twitch.tv/api/users/shydragon88/follows/games/Destiny

[D] :31 - HTTP: 404 Not Found

[D] QGstreamerVideoWindow::QGstreamerVideoWindow:72 - No m_videoSink available!

[W] unknown:151 - file:///usr/share/harbour-twitchtube/qml/pages/StreamPage.qml:151: TypeError: Cannot rea
d property 'mobile' of undefined

[W] unknown:24 - file:///usr/share/harbour-twitchtube/qml/cover/NavigationCover.qml:24:26:
Unable to assign [undefined] to QString

[D] Tools::setBlankingMode:62 - Screen blanking turned off

[D] logAvailability:199 - video availability: undefined

[D] onSourceChanged:53 - 234 374

[D] onSourceChanged:54 - 0 0

[D] IrcChat::onSockStateChanged:177 - QAbstractSocket::ConnectedState

[D] :30 - Error accessing url
https://api.twitch.tv/kraken/users/shydragon88/follows/channels/kinggothalion

[D] :31 - HTTP: 404 Not Found

[D] logState:216 - video state: playing
(harbour-twitchtube:24446): GStreamer-CRITICAL **:
gst_mini_object_unref: assertion 'mini_object->refcount> 0' failed
...

[D] logState:216 - video state: paused

[D] IrcChat::onSockStateChanged:177  QAbstractSocket::UnconnectedState
</code>

**Comment by Aldrog** [comment]
Turned out it's needed to repeat requests for screen blanking pause periodically (every 60 seconds at least). Otherwise system simply thinks the app's stopped and cancels the requested pause. [Here's an update](https://github.com/Aldrog/TwitchTube/releases/download/v1.0.0-alpha.3/harbour-twitchtube-0.90.2-1.armv7hl.rpm) with this taken in account.

**Comment by Termitebug** [comment]
Well done! I tested the -0.90.2-1 version of a 5 minutes continuous watching and the issue is solved. This can be closed now. Thanks :+1:

**Comment by Aldrog** [comment]
@Termitebug thank you a lot for your help :+1: . Now I need a few days to finish the chat issue #4 and 1.0 is ready :smile:
