### ISSUE TITLE
Display offline channels in Followed Channels section

### ISSUE THREAD

**Issue by JoshStrobl** [Aldrog/TwitchTube#7]
Issue: Followed Channels only shows those who are currently broadcasting
Expected Behavior: Shows both those who are live and offline.

Is this a bug or is this intentional until past broadcasts are implemented?

**Comment by Aldrog** [comment]
That's not a bug. I don't see any purpose in displaying offline channels when neither past broadcasts nor even viewing channel profiles is implemented.

**Comment by JoshStrobl** [comment]
> I don't see any purpose in displaying offline channels when neither past broadcasts nor even viewing channel profiles is implemented.

Which is why I asked:

> [...] is this intentional until past broadcasts are implemented?

You could, ya know, keep the issue open and use it to track actually implementing the feature, rather than just immediately closing it.

**Comment by Aldrog** [comment]
Sorry, I'm not that experienced with Github. I'll follow your advice and reopen the issue.

**Comment by Aldrog** [comment]
As I'm slowly returning to TwitchTube development, here goes a task list for this issue:
- [x] Support multiple grids in page on component level (**Done** in d2c645c45386a8276285378250da1de41bf16e10)
- [x] Display additional grid of followed channels below followed streams (**Done** in 60e6ffc4dbfd983750bcdae162584eced1703cbe)
- [x] Design channel page with highlights and past broadcasts (**Done** in 81dc791c137227004fbfeabcdc4d37bcc6667834 and 6c6d943d397be71963241f8fc5b81aa6283128bd)
- [x] Link to channel page from followed channels and from stream player (**Done** in e815ccf1332f96b5c0bd17da277b88363d5e4892)
- [x] Add separate player for static videos - with timeline and without chat (**Done** in 67129e381fb7f0ead83447edb90c4fa4538239e2...bdd85961a9e1657e96f9038af37afd4f467fb6c2)

**Comment by Aldrog** [comment]
Past broadcasts are finally implemented and TwitchTube 1.2 is already in the Store.
Thanks to Lauri Johansson at Jolla QA for the feedback :)
